      gateway:
        type: object
        additionalProperties: false
        required: [name]
        properties:
          name:
            type: string
            description: |
              The name of your Gateway for this route.
          namespace:
            type: string
            description: |
              The namespace the Gateway is running in.
          sectionName:
            type: string
            description: |
              The name of the Gateway listener section to route traffic to.
              Common values are 'http', 'https', or custom listener names.
